name: Daily OS 8

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v4

    - name: Build daily .iso
      run: |
        ./workflows.sh etc/terraform-daily-8.0-azure.conf "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}"
    
    - name: Upload daily .iso artifact
      uses: actions/upload-artifact@v4
      with:
        name: daily-8.0-iso
        path: builds/amd64/*.iso
